lib: fix list items missing indentation
Fixes a clippy finding of the form:

```
error: doc list item missing indentation
   --> src/lib.rs:109:4
    |
109 | //! for sequences and sets variants
    |    ^
    |
    = help: if this is supposed to be its own paragraph, add a blank line
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_lazy_continuation
    = note: `-D clippy::doc-lazy-continuation` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::doc_lazy_continuation)]`
```