Cargo: add missing bitvec feature
Fixes clippy finding of the form:

```
error: unexpected `cfg` condition value: `bitvec`
  --> src/ber/ber.rs:13:7
   |
13 | #[cfg(feature = "bitvec")]
   |       ^^^^^^^^^^^^^^^^^^
   |
   = note: expected values for `feature` are: `bigint`, `cookie-factory`, `default`, `num-bigint`, `serialize`, `std`, and `unstable`
   = help: consider adding `bitvec` as a feature in `Cargo.toml`
   = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
   = note: `-D unexpected-cfgs` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(unexpected_cfgs)]`
```